/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.math.DoubleMath;

import java.math.RoundingMode;

public class HelloOtus {
    public static void main(String... args) {
        double number = 4.6;
        int rounded = DoubleMath.roundToInt(number, RoundingMode.HALF_UP);
        System.out.println(rounded);
    }
}
